on:
  push:
    branches:
      - 'master'
  pull_request:

name: CI

jobs:
  build:
    name: CI
    strategy:
      matrix:
        nextcloudVersion: [ v23.0.0, master ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phpunit

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          git clone --depth 1 https://github.com/nextcloud/server.git -b ${{ matrix.nextcloudVersion }}
          cd server && git submodule update --init
          ./occ maintenance:install --admin-pass=admin

      - name: PHP stan
        run: make phpstan

      - name: PHP code style
        run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )

      - name: Install NPM Dependencies
        run: npm install

      - name: JS Lint
        run: npm run lint

      - name: Style Lint
        run: npm run stylelint

      - name: PHP & Vue Unit Tests
        run: make test
