on: [ push, pull_request ]

name: CI

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phpunit

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install PHP Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Style Lint
        run: npm run stylelint

      - name: Vue Unit Tests
        run: npm run test:unit

      - name: PHP Unit Tests
        run: make test
