on: [ push, pull_request ]

name: CI

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Style Lint
        run: npm run stylelint

      - name: Unit Tests
        run: npm run test:unit
